version: "3.8"

services:
  frontend:
    build:
      context: ./path/to/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5001"
    networks:
      - app-network
    restart: unless-stopped

  ollama:
    image: relaximus/mistral-ollama # use onlydole/ollama-mistral for arm64
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - app-network
    restart: unless-stopped

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true" # Expose Traefik dashboard
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Dashboard
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
